

post http://localhost:8080/users/signup
Content-Type: application/json

{
    "email":"james@gmail.com",
    "password":"1234567",
    "course":"Accounting",
    "year":1,
    "name":"james",
    "surname":"doe"
}

###
post http://localhost:8080/quiz
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWZjOWMwYjc3NDhkZTYzZmJkNDU2MiIsImlhdCI6MTY5MzQzNjM1MiwiZXhwIjoxNjkzNjk1NTUyfQ.rUUjmsVLN0fi2lgDPo4Kjlp7UUcdf6PYDqtHVB94qMs

{
    "Extroversion":12,
    "Agreeableness":23,
    "Conscientiousness":12,
    "Neuroticism":31,
    "OpennessExperience":32,
    "group":"Introvert-Stable"
   
}

###
post http://localhost:8080/message
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWZjOWMwYjc3NDhkZTYzZmJkNDU2MiIsImlhdCI6MTY5MzQzNjM1MiwiZXhwIjoxNjkzNjk1NTUyfQ.rUUjmsVLN0fi2lgDPo4Kjlp7UUcdf6PYDqtHVB94qMs

{
    "groupChatId":"64efd2cbe0a02e58c0a6562e",
    "senderId":"64efc9c0b7748de63fbd4562",
    "text":"Introvert-Stable"
   
}


